### ISSUE TITLE
Nothing happens when i click connect button

### ISSUE THREAD

**Issue by khanakia** [grafbase/pathfinder#162]
I am using shopify graphql api https://xxx.myshopify.com/admin/api/2023-07/graphql.json

and also i passed the `X-Shopify-Access-Token` as headers

After i click the Connect nothing happens

![Screenshot 2023-10-16 at 10 28 09 AM](https://github.com/grafbase/pathfinder/assets/2174170/76c7745a-7312-443b-8e2d-1645ac199353)

**Comment by jonathanawesome** [comment]
With Shopify, this could be a number of things. We haven't done much internal testing here, but I imagine that this is a CORS error and that Shopify is preventing front-end/fetch. Our desktop app is a simple wrapper around the web app...we'll be upgrading this in the future, but for now that's what we have.

Insomnia works for me with my test store and properly configured access_token, so I'm going to go ahead and say this is a  front-end/fetch thing.
