### ISSUE TITLE
Add a way to instantly add all properties for return in a resolver

### ISSUE THREAD

**Issue by nikitavoloboev** [grafbase/pathfinder#259]
In [EdgeDB](https://www.edgedb.com) query language you can use `*` to achieve this:

<img width="1284" alt="image" src="https://github.com/grafbase/pathfinder/assets/6391776/d23d7d50-4560-441c-ab1f-bdf6cf68cedd">

In Pathfinder, to make a query like this:

<img width="1276" alt="image" src="https://github.com/grafbase/pathfinder/assets/6391776/a8036ee4-a989-42f6-9379-3f831b23c47e">

I had to click 10+ times..

As `*` is not a valid GraphQL. Perhaps one way to solve this is to provide a button here:

![CleanShot 2024-01-06 at 16 45 49@2x](https://github.com/grafbase/pathfinder/assets/6391776/5e32717f-e000-4e7a-af78-69869430103b)

That will say `Add all return properties` and it will do above instantly.

**Comment by jonathanawesome** [comment]
This isn't really possible with GraphQL. We can't automatically build a "complete" selection set because fields can be infinitely nested.
