### ISSUE TITLE
Add palette search for Query/Mutation to paste

### ISSUE THREAD

**Issue by nikitavoloboev** [grafbase/pathfinder#71]
Provide one of these palettes on `cmd+k` 

<img width="558" alt="image" src="https://github.com/grafbase/pathfinder/assets/6391776/0c23882a-c29b-42c6-a1e3-5d3e37a9acfe">

Where inside it you will get a list of query/mutation found here:

<img width="317" alt="image" src="https://github.com/grafbase/pathfinder/assets/6391776/76c3165d-71ec-4bd7-aa25-65c8f330f5a0">

`getGlobalLinks` etc.

And on enter, it would do the same as clicking on the query in UI. Together with #70 would allow to use Pathfinder fully from keyboard which would be great.

**Comment by jonathanawesome** [comment]
Closing, as `monaco-graphql` offers auto complete that is basically this feature.
