### ISSUE TITLE
Need multiple headers for graphql introspection on app start

### ISSUE THREAD

**Issue by nullxone** [grafbase/pathfinder#81]
I would like to add multiple header values on start, without which I cannot progress past the initial screen and begin to use the app. I get the error "Response not OK. Do you need to add headers?" (yes, I do)

My GraphQL server needs both an auth header and another to set the content type for introspection to work.

As an alternative, can we please not have a the initial screen and instead configure headers and the endpoint in the main app?

v0.1.1 on macos

**Comment by nullxone** [comment]
As an alternative, can the client always add "Content-Type: application/json" to all queries? That would work as well!

**Comment by yoav-lavi** [comment]
@nullxone We definitely want to do the former option, but the latter option (default content-type header) should be ready very soon!

**Comment by jonathanawesome** [comment]
thanks for the issue, tracking in #93.
