### ISSUE TITLE
Won't load any GraphQL endpoints

### ISSUE THREAD

**Issue by nathanchapman** [grafbase/pathfinder#89]
Trying to get past the initial launch screen but I'm getting this error message with every GraphQL endpoint I try, including locally running endpoints and well-known public endpoints with introspection enabled:

```
Response not OK. Do you need to add headers?
```

<img width="638" alt="image" src="https://github.com/grafbase/pathfinder/assets/4032071/e260ce02-dc62-4393-a3b8-231b219f16a3">

**Comment by fbjork** [comment]
@nathanchapman thanks for reporting this issue. The problem is we are not sending the Content-Type: application/json header by default. This will be fixed in the next release later this week. For now you can set it yourself when creating a new session.

**Comment by nathanchapman** [comment]
That worked. Thanks, Fredrik!

**Comment by jonathanawesome** [comment]
fixed in #93
